<<<<<<< HEAD
- hosts: all
  tasks:
  - name: Install Prerequisites
    yum:
      name:
      - vim
      - epel-release
      - kernel
    register: yum
  - name: Disable SELinux
    selinux:
      state: disabled
    register: selinux
  - name: Reboot
    reboot:
      reboot_timeout: 600
    when: yum.changed or selinux.changed
  - name: Install PHP
    include_tasks: php.yml

  - name: Install Apache
    include_tasks: apache.yml

  - name: Install WordPress
    include_tasks: wordpress.yml

  - name: Install WordPress
    include_tasks: mysql.yml
    when: local_mysql
=======
- hosts: web
  tasks:
  - include_tasks: hostname.yml
>>>>>>> 4bdf1a5faa49ed0f67129869e0e89ba0989a13b9
