---
- name: Install packages
  become: yes
  become_method: sudo
  user: ec2-user
  hosts: all
  tasks:
  - name: Install Apache
    package:
      name: "{{item}}"
      state: latest
    with_items:
    - telnet
    - gzip
    - lftp
    - httpd
    - vsftpd
