- hosts: web
  task:
  - name: Install Httpd
    yum:
      name: httpd
      state: latest

  - name: Start httpd
    systemd:
      name: httpd
      state: started
  - name: Enable httpd
    systemd:
      name: httpd
      ebabled: yes
      masked: no
- hosts: web
  task: Download templates
  get_url:
    url: https://www.free-css.com/assets/files/free-css-templates/download/page258/sentra.zip
    dest: /etc/httpd/www/html
- host: web
  task:
  - name: unzip
    yum:
      name: unzip
      state: latest
  - name: unzip file
    unarchive:
      src: /var/www/html/sentra.zip
      dest: /var/www/html
      remote_src: yes
- hosts: web
  tasks:
  - name: move files


